version: "2"
services:

  # Elasticsearch Docker Image

  # Filebeat Docker Image
  filebeat:
    image: "docker.elastic.co/beats/filebeat:5.4.3"
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log:/mnt/log:ro

  # Use bridge network for all the container, keeping all the container in same network will simplify the communication between the container.